verifyDepsBeforeRun: false
minimumReleaseAgeExclude:
  - dsh-calendar@0.9.0
  - dsh-cite@0.3.4
  - dsh-code-security@0.3.4
  - dsh-codex-port@0.2.3
  - dsh-email@0.14.1
  - dsh-ffmpeg@0.4.3
  - dsh-minimal-ptc@0.5.1
  - dsh-ppt@0.5.0
  - dsh-remotion@0.3.2
  - dsh-rss@0.4.1
  - dsh-slack@0.3.1
  - dsh-sql@0.4.3
  - dsh-voice@0.3.4
